### ISSUE TITLE
Crash in 1.12.2

### ISSUE THREAD

**Issue by XvaleX10** [dragon-forge/HammerLib#43] opened 2023-10-26 14:23 UTC
[crash-2023-10-26_16.15.21-server.txt](https://github.com/dragon-forge/HammerLib/files/13178836/crash-2023-10-26_16.15.21-server.txt)
This time the crash is different, can it be resolved?

**Comment by Zeitheron** [comment] 2023-10-26 14:27
Duplicate of #41

**Closed as not planned by Zeitheron** 2023-10-26 14:27 UTC
